Repository DFE-Digital/find-teacher-training, pull requests merged in 2020-02, with the labels that each got.

#111 2968 - Change how we load in Google Analytics
  app/views/layouts/application.html.erb
  app/webpacker/packs/application.js
  app/webpacker/scripts/__snapshots__/analytics.spec.js.snap
  app/webpacker/scripts/analytics.js
  app/webpacker/scripts/analytics.spec.js
Labels: cookie-banner-consent

#112 2968 Hide cookie banner on cookie page
  app/views/layouts/application.html.erb
  spec/features/cookie_banner_spec.rb
Labels: cookie-banner-consent

#118 2968 cookies
  app/controllers/cookie_preferences_controller.rb
  app/controllers/pages_controller.rb
  app/views/cookie_preferences/_cookie-preferences-form.html.erb
  app/views/cookie_preferences/_error_message.html.erb
  app/views/cookie_preferences/new.html.erb
  app/views/layouts/_cookie-banner.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/cookie_preferences.html.erb
  app/views/result_filters/location/_form.html.erb
  app/views/result_filters/qualification/new.html.erb
  app/views/result_filters/study_type/new.html.erb
  app/views/result_filters/subject/_form.html.erb
  app/views/shared/_error_message.html.erb
  app/webpacker/packs/application.js
  app/webpacker/scripts/analytics.js
  app/webpacker/scripts/analytics.spec.js
  app/webpacker/scripts/cookie-banner.js
  app/webpacker/scripts/cookie-banner.spec.js
  app/webpacker/scripts/cookie-helper.js
  app/webpacker/scripts/cookie-helper.spec.js
  app/webpacker/scripts/copy-tracking.js
  app/webpacker/scripts/no-results-tracking.js
  app/webpacker/scripts/scroll-tracking.js
  config/locales/en.yml
  config/routes.rb
  spec/controllers/cookie_preferences_controller_spec.rb
  spec/features/cookie_banner_spec.rb
  spec/features/cookie_consent_spec.rb
  spec/features/view_pages_spec.rb
  spec/site_prism/page_objects/page/cookie_preferences.rb
Labels: cookie-banner-consent

#165 [3057] - Fix course count
  app/view_objects/results_view.rb
  spec/fixtures/api_responses/courses.json
Labels: bug

#151 [3044] Add location filtering
  app/view_objects/results_view.rb
  app/views/results/_location.html.erb
  spec/features/result_filters/location_spec.rb
  spec/features/results_spec.rb
  spec/view_objects/results_view_spec.rb
Labels: do not merge
