Repository DFE-Digital/find-teacher-training, pull requests merged in 2021-02, with the labels that each got.

#635 Manage secrets in KeyVault
  .github/workflows/deploy.yml
  terraform/data.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/sandbox.tfvars
  terraform/workspace_variables/staging.tfvars
Labels: DevOps

#638 Update entry requirements partial to use standardised content
  app/components/advice_component.html.erb
  app/components/advice_component.rb
  app/views/courses/_entry_requirements.html.erb
  app/views/courses/_entry_requirements_qualifications.html.erb
  app/webpacker/styles/application.scss
  app/webpacker/styles/components/_advice.scss
Labels: do not merge

#640 Update financial support partial to use standardised content
  app/views/courses/_fees_and_financial_support.html.erb
Labels: do not merge

#670 Validate secrets in deploy workflow before running terraform
  .github/workflows/deploy.yml
  .gitignore
  Makefile
  terraform/workspace_variables/production.sh
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/qa.sh
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/sandbox.sh
  terraform/workspace_variables/sandbox.tfvars
  terraform/workspace_variables/staging.sh
  terraform/workspace_variables/staging.tfvars
Labels: DevOps

#671 Default filters to show courses with vacancies by default | Fix missing params
  app/view_objects/result_filters/new_filters_view.rb
  app/view_objects/results_view.rb
  app/views/new_filters/_all.html.erb
  app/views/new_filters/_hidden_fields.html.erb
  app/views/new_filters/_study_type_filter.html.erb
  app/views/new_filters/_vacancy_filter.html.erb
  spec/features/new_results_page_filters/location_and_provider_spec.rb
  spec/features/new_results_page_filters/qualifications_spec.rb
  spec/features/new_results_page_filters/salary_spec.rb
  spec/features/new_results_page_filters/send_spec.rb
  spec/features/new_results_page_filters/study_type_spec.rb
  spec/features/new_results_page_filters/subjects_spec.rb
  spec/features/new_results_page_filters/vacancies_spec.rb
  spec/features/result_filters/funding_spec.rb
  spec/features/result_filters/location_spec.rb
  spec/features/result_filters/qualifications_spec.rb
  spec/features/result_filters/study_type_spec.rb
  spec/features/result_filters/subjects_spec.rb
  spec/features/result_filters/vacancy_spec.rb
  spec/features/results_spec.rb
  spec/support/geocoder_helper.rb
  spec/support/results_page_parameters.rb
  spec/view_objects/result_filters/new_filters_view_spec.rb
  spec/view_objects/results_view_spec.rb
Labels: bug, enhancement

#682 TTAPI PaaS for testing
  config/settings/staging.yml
Labels: DevOps

#685 Add make console to Makefile
  Makefile
Labels: DevOps
