Repository DFE-Digital/find-teacher-training, pull requests merged in 2021-09, with the labels that each got.

#921 Deploy review apps
  .github/workflows/build.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .github/workflows/smoke-test.yml
  Makefile
  config/environments/review.rb
  config/settings/review.yml
  docker-compose.yml
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/app_config.yml
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/review.sh
  terraform/workspace_variables/review.tfvars
  terraform/workspace_variables/review_backend.tfvars
  terraform/workspace_variables/sandbox.tfvars
  terraform/workspace_variables/staging.tfvars
Labels: DevOps, deploy

#799 Update govuk-components to v2
  Gemfile
  Gemfile.lock
  app/components/deadline_banner_component.html.erb
  app/components/summary_list_component.html.erb
  app/components/summary_list_component.rb
  app/helpers/view_helper.rb
  app/views/courses/_apply_button.html.erb
  app/views/courses/_no_vacancies_warning.html.erb
  app/views/courses/qualification/_pgce.html.erb
  app/views/courses/qualification/_pgce_with_qts.html.erb
  app/views/courses/qualification/_pgde.html.erb
  app/views/courses/qualification/_pgde_with_qts.html.erb
  app/views/courses/qualification/_qts.html.erb
  app/views/kaminari/_next_page.html.erb
  app/views/kaminari/_prev_page.html.erb
  app/views/layouts/application.html.erb
  app/views/result_filters/provider/new.html.erb
  app/views/result_filters/subject/_form.html.erb
  app/views/results/_university.html.erb
  app/views/results/index.html.erb
  app/webpacker/scripts/cookie-banner.js
  app/webpacker/scripts/cookie-banner.spec.js
  spec/components/summary_list_component_spec.rb
  spec/features/cookie_banner_spec.rb
Labels: Components

#935 Add visa sponsorship filter to results page
  app/view_objects/result_filters/filters_view.rb
  app/view_objects/results_view.rb
  app/views/result_filters/_all.html.erb
  app/views/result_filters/_visa_filter.html.erb
  config/settings.yml
  config/settings/qa.yml
  config/settings/review.yml
  config/settings/test.yml
  spec/features/result_filters/visa_spec.rb
  spec/site_prism/page_objects/page/results.rb
  spec/view_objects/result_filters/filters_view_spec.rb
Labels: deploy

#937 No search results page - amends
  app/components/courses/no_results_component.html.erb
  app/components/courses/no_results_component.rb
  app/components/location_subject_filter_component.html.erb
  app/view_objects/results_view.rb
  app/views/results/_funding.html.erb
  app/views/results/_location.html.erb
  app/views/results/_no_results.html.erb
  app/views/results/_provider.html.erb
  app/views/results/_qualifications.html.erb
  app/views/results/_subjects.html.erb
  app/views/results/_try_another_search_text.html.erb
  app/views/results/_vacancy.html.erb
  app/views/results/index.html.erb
  spec/components/courses/no_results_component_spec.rb
  spec/components/location_subject_filter_component_spec.rb
  spec/view_objects/results_view_spec.rb
  spec/views/results/no_results_spec.rb
  spec/views/results/try_another_search_text_spec.rb
Labels: deploy

#940 Return 'next year' if cycle switcher has been set to 'find has reopened'
  app/controllers/switcher_controller.rb
  app/models/site_setting.rb
  app/services/cycle_timetable.rb
  spec/requests/cycles_spec.rb
  spec/services/cycle_timetable_spec.rb
Labels: bug

#959 Configure assets domain for serving static assets
  config/environments/production.rb
  config/initializers/assets_cache_headers.rb
  config/settings/production.yml
  config/settings/qa.yml
  config/settings/sandbox.yml
  config/settings/staging.yml
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
Labels: DevOps

#964 Remove www2 sub-domain
  config/routes.rb
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
Labels: DevOps

#978 Add maintenance page and flag for when find is down
  app/components/maintenance_banner_component.html.erb
  app/components/maintenance_banner_component.rb
  app/controllers/application_controller.rb
  app/controllers/pages_controller.rb
  app/views/layouts/application.html.erb
  app/views/pages/maintainance.html.erb
  config/routes.rb
  config/settings.yml
  spec/components/maintenance_banner_component_spec.rb
  spec/features/maintainance_page_spec.rb
  spec/features/maintenance_banner_spec.rb
Labels: deploy

#982 Turn off maintenance banner
  config/settings.yml
Labels: DevOps

#987 Configure redis cache store
  config/environments/production.rb
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
Labels: DevOps

#994 Use existing redis connection for checking SiteSettings
  app/lib/redis.rb
  app/models/site_setting.rb
Labels: DevOps

#988 [2261] Stop logging Bigquery job
  app/job/send_event_to_big_query_job.rb
Labels: DevOps, deploy

#1005 Use net_http_persistent for better performance when making API calls
  Gemfile
  Gemfile.lock
  app/controllers/heartbeat_controller.rb
  app/models/base.rb
  app/services/location_suggestion.rb
Labels: deploy

#1007 [2261] Set Sidekiq log level to WARN
  config/initializers/sidekiq.rb
Labels: deploy
