Repository DFE-Digital/find-teacher-training, pull requests merged in 2021-12, with the labels that each got.

#1101 [4128] - Componentise course page
  app/components/courses/about_schools_component.html.erb
  app/components/courses/about_schools_component.rb
  app/components/courses/apply_component.html.erb
  app/components/courses/apply_component.rb
  app/components/courses/contact_details_component.html.erb
  app/components/courses/contact_details_component.rb
  app/components/courses/contents_component.html.erb
  app/components/courses/contents_component.rb
  app/components/courses/fees_and_financial_support_component.html.erb
  app/components/courses/fees_and_financial_support_component.rb
  app/components/courses/fees_component.html.erb
  app/components/courses/fees_component.rb
  app/components/courses/financial_support/bursary_component.html.erb
  app/components/courses/financial_support/bursary_component.rb
  app/components/courses/financial_support/scholarship_and_bursary_component.html.erb
  app/components/courses/financial_support/scholarship_and_bursary_component.rb
  app/components/courses/qualifications_summary_component.html.erb
  app/components/courses/qualifications_summary_component.rb
  app/components/courses/summary_component.html.erb
  app/components/courses/summary_component.rb
  app/decorators/course_decorator.rb
  app/views/courses/_about_schools.html.erb
  app/views/courses/_apply_button.html.erb
  app/views/courses/_fees_and_financial_support.html.erb
  app/views/courses/_no_vacancies_warning.html.erb
  app/views/courses/placement/_hei.html.erb
  app/views/courses/placement/_scitt.html.erb
  app/views/courses/show.html.erb
  spec/components/courses/about_schools_component_spec.rb
  spec/components/courses/apply_component_spec.rb
  spec/components/courses/contact_details_component_spec.rb
  spec/components/courses/contents_component_spec.rb
  spec/components/courses/fees_and_financial_support_component_spec.rb
  spec/components/courses/financial_support/bursary_component_spec.rb
  spec/components/courses/financial_support/scholarship_and_bursary_component_spec.rb
  spec/components/courses/qualifications_summary_component_spec.rb
  spec/components/courses/summary_component_spec.rb
  spec/decorators/course_decorator_spec.rb
  spec/features/courses/show_spec.rb
Labels: refactor

#1105 [4170] - Refactor results page filters feature specs
  spec/features/result_filters/qualifications_spec.rb
  spec/features/result_filters/required_degree_spec.rb
  spec/features/result_filters/salary_spec.rb
  spec/features/result_filters/send_spec.rb
  spec/features/result_filters/study_type_spec.rb
  spec/features/result_filters/vacancies_spec.rb
  spec/features/result_filters/visa_spec.rb
  spec/features/result_page_filters/qualifications_spec.rb
  spec/features/result_page_filters/required_degree_spec.rb
  spec/features/result_page_filters/salary_spec.rb
  spec/features/result_page_filters/send_spec.rb
  spec/features/result_page_filters/study_type_spec.rb
  spec/features/result_page_filters/vacancies_spec.rb
  spec/features/result_page_filters/visa_spec.rb
  spec/features/search/location_and_provider_spec.rb
  spec/features/search/subjects_spec.rb
  spec/features/suggested_searches_spec.rb
  spec/site_prism/page_objects/page/result_filters/location_filter_results.rb
  spec/site_prism/page_objects/page/result_page_filters/funding.rb
  spec/site_prism/page_objects/page/result_page_filters/qualification.rb
  spec/site_prism/page_objects/page/result_page_filters/study_type.rb
  spec/site_prism/page_objects/page/result_page_filters/vacancy.rb
  spec/site_prism/page_objects/page/search/location.rb
  spec/site_prism/page_objects/page/search/provider_page.rb
  spec/site_prism/page_objects/page/search/subject_page.rb
  spec/site_prism/page_objects/page/start.rb
  spec/support/filters_feature_specs_helper.rb
Labels: refactor

#1110 [3928] - new search flow
  app/components/hidden_fields_component.html.erb
  app/components/hidden_fields_component.rb
  app/components/search/primary_subject_selection_component.html.erb
  app/components/search/primary_subject_selection_component.rb
  app/components/search/secondary_subject_selection_component.html.erb
  app/components/search/secondary_subject_selection_component.rb
  app/controllers/result_filters/location_controller.rb
  app/controllers/search/age_groups_controller.rb
  app/controllers/search/subjects_controller.rb
  app/form_objects/search/age_groups_form.rb
  app/form_objects/search/subjects_form.rb
  app/lib/feature_flags.rb
  app/views/result_filters/subject/start.html.erb
  app/views/search/age_groups/new.html.erb
  app/views/search/subjects/new.html.erb
  config/locales/age_groups.yml
  config/locales/subjects.yml
  config/routes.rb
  spec/features/search/new_flow/across_england/further_education_spec.rb
  spec/features/search/new_flow/across_england/primary_spec.rb
  spec/features/search/new_flow/across_england/secondary_spec.rb
  spec/features/search/new_flow/editing_a_search_spec.rb
  spec/form_objects/search/age_groups_form_spec.rb
  spec/form_objects/search/subjects_form_spec.rb
Labels: deploy

#1119 Remove notifications from smoke test for review
  .github/workflows/smoke-test.yml
Labels: DevOps
