Repository DFE-Digital/find-teacher-training, pull requests merged in 2022-02, with the labels that each got.

#1198 [513] Rightscale find
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.tfvars.json
Labels: DevOps

#1200 Add worklow to refresh docker cache weekly
  .github/workflows/build-nocache.yml
  .github/workflows/build.yml
  Dockerfile
  docs/deployment.md
Labels: DevOps, deploy

#1207 Stop dependabot builds from running the SNYK scan
  .github/workflows/build.yml
Labels: DevOps

#1138 Update content for International Candidates section
  app/components/courses/contents_component.html.erb
  app/components/courses/international_students_component.html.erb
  app/components/courses/international_students_component.rb
  spec/components/courses/international_students_component_spec.rb
  spec/features/courses/show_spec.rb
Labels: deploy

#1224 Migrate to GitHub container registry
  .github/workflows/build-nocache.yml
  .github/workflows/build.yml
  Makefile
  docker-compose.yml
  docs/deployment.md
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
Labels: deploy

#1220 Add check to bursary component
  app/components/courses/financial_support/bursary_component.html.erb
  app/components/courses/financial_support/bursary_component.rb
  spec/components/courses/financial_support/bursary_component_spec.rb
Labels: deploy

#1231 Use email address as link text for mailto
  app/views/layouts/application.html.erb
Labels: deploy

#1235 Allow dependabot triggered PRs to login into GHCR
  .github/workflows/build.yml
Labels: deploy
