Repository DFE-Digital/find-teacher-training, pull requests merged in 2022-07, with the labels that each got.

#1394 [273] Update content on course info
  app/components/courses/contents_component.html.erb
  app/views/courses/_about_course.html.erb
Labels: deploy

#1399 Upgrade Terraform to 0.14.11
  .github/actions/deploy/action.yml
  .github/workflows/delete-review-app.yml
  .tool-versions
  docs/deployment.md
  terraform/.terraform.lock.hcl
  terraform/modules/statuscake/providers.tf
  terraform/terraform.tf
Labels: deploy

#1411 Fix ncurses-terminfo-base vulnerability
  Dockerfile
Labels: DevOps

#1413 246 update dates on current point in the recruitment cycle page
  app/helpers/current_point_in_recruitment_cycle_helper.rb
  app/services/cycle_timetable.rb
  app/views/switcher/cycles.html.erb
Labels: deploy

#1417 Remove StatusCake alerts
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/rollover.tfvars.json
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.tfvars.json
Labels: DevOps, deploy

#1418 Update Terraform providers
  docs/deployment.md
  terraform/.terraform.lock.hcl
  terraform/modules/paas/main.tf
  terraform/modules/statuscake/main.tf
  terraform/modules/statuscake/providers.tf
  terraform/terraform.tf
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/rollover.tfvars.json
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.tfvars.json
Labels: DevOps, deploy
