Repository DFE-Digital/find-teacher-training, pull requests merged in 2022-08, with the labels that each got.

#1423 346 Content Security Policy
  app/views/layouts/_add_js_enabled_class_to_body.html.erb
  app/views/layouts/application.html.erb
  config/initializers/content_security_policy.rb
Labels: deploy

#1431 fix or remove illogical headings
  app/views/courses/_advice.html.erb
Labels: deploy

#1435 [365] Update the Ruby version to 3.1.0
  .rubocop.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  app/components/feature_toggle_component.rb
  app/components/utility/summary_card_component.rb
  app/components/utility/summary_list_component.rb
  app/controllers/heartbeat_controller.rb
  app/controllers/results_controller.rb
  app/lib/feature_flag.rb
  app/models/base.rb
  app/services/location_suggestion.rb
  app/services/teacher_training_public_api/sync_all_providers.rb
  app/services/unescaped_query_string_service.rb
  app/view_objects/results_view.rb
  app/view_objects/suggested_search_link.rb
  app/views/courses/show.html.erb
  app/views/result_filters/location/new.html.erb
  app/views/search/age_groups/new.html.erb
  app/views/search/subjects/new.html.erb
  lib/tasks/rubocop.rake
  spec/components/courses/about_schools_component_spec.rb
  spec/components/courses/apply_component_spec.rb
  spec/components/courses/contact_details_component_spec.rb
  spec/components/courses/contents_component_spec.rb
  spec/components/courses/entry_requirements_component_spec.rb
  spec/components/courses/search_result_component_spec.rb
  spec/components/courses/summary_component_spec.rb
  spec/components/location_subject_filter_component_spec.rb
  spec/components/results/results_component_spec.rb
  spec/components/results/search_result_component_spec.rb
  spec/components/utility/summary_card_component_spec.rb
  spec/components/utility/summary_list_component_spec.rb
  spec/controllers/concerns/filter_parameters_spec.rb
  spec/controllers/courses_controller_spec.rb
  spec/decorators/course_decorator_spec.rb
  spec/features/courses/show_spec.rb
  spec/features/suggested_searches_spec.rb
  spec/form_objects/search/age_groups_form_spec.rb
  spec/rails_helper.rb
  spec/requests/location_suggestions_spec.rb
  spec/requests/sitemaps_spec.rb
  spec/services/deprecated_parameters_service_spec.rb
  spec/services/location_suggestion_spec.rb
  spec/services/teacher_training_public_api/sync_all_providers_spec.rb
  spec/support/stub_api_v3_resource.rb
  spec/support/stub_v3_helper.rb
  spec/support/stubbed_requests/courses.rb
  spec/support/stubbed_requests/providers.rb
  spec/view_objects/result_filters/filters_view_spec.rb
  spec/view_objects/result_filters/qualification_view_spec.rb
  spec/view_objects/results_view_spec.rb
  spec/view_objects/suggested_search_link_spec.rb
  spec/views/results/non_university_spec.rb
  spec/views/results/university_spec.rb
  spec/views/shared/hidden_previous_fields_spec.rb
Labels: deploy

#1440 346 csp external scripts v2
  app/views/layouts/_add_js_enabled_class_to_body.html.erb
  app/views/layouts/application.html.erb
  config/initializers/content_security_policy.rb
Labels: deploy

#1449 Remove manual add of zlib r3
  Dockerfile
Labels: DevOps

#1463 [292] Disable external logging in load test environment
  terraform/.terraform.lock.hcl
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/loadtest.tfvars.json
Labels: DevOps

#1468 Update Terraform StatusCake provider to 2.0.3
  docs/deployment.md
  terraform/.terraform.lock.hcl
  terraform/modules/statuscake/providers.tf
  terraform/terraform.tf
Labels: DevOps, deploy
