Repository DFE-Digital/find-teacher-training, pull requests merged in 2022-04, with the labels that each got.

#1278 Base Image Vulnerability fixes
  Dockerfile
Labels: DevOps, deploy

#1289 Use workflow concurrency
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy.yml
Labels: DevOps, deploy

#1300 Quick copy edit
  app/components/results/results_component.html.erb
  spec/components/results/results_component_spec.rb
Labels: deploy

#1313 Redesign promoted event link
  app/components/results/results_component.html.erb
  app/webpacker/styles/application.scss
  app/webpacker/styles/components/_promoted-link.scss
Labels: content
