Repository DFE-Digital/find-teacher-training, pull requests merged in 2022-10, with the labels that each got.

#1534 [614] Put stop gap for UCL's contact form
  app/components/courses/contact_details_component.html.erb
Labels: deploy

#1532 Remove terraform from dependabot checks
  .github/dependabot.yml
Labels: DevOps

#1545 [701] Pin Github actions to the major version
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
Labels: DevOps, deploy

#1550 Stop using set-output in workflows
  .github/actions/deploy/action.yml
Labels: DevOps, github_actions, deploy

#1555 Use subject name not course title for qualifications needed
  app/components/courses/entry_requirements_component.rb
  app/decorators/course_decorator.rb
  spec/components/courses/entry_requirements_component_spec.rb
  spec/decorators/course_decorator_spec.rb
Labels: deploy
