Repository DFE-Digital/find-teacher-training, pull requests merged in 2022-01, with the labels that each got.

#1118 [4209] - Wire up provider search to the new flow
  app/controllers/result_filters/provider_controller.rb
  spec/features/search/location_and_provider_spec.rb
  spec/features/search/new_flow/location_spec.rb
  spec/features/search/new_flow/provider_spec.rb
  spec/features/search/subjects_spec.rb
Labels: deploy, new search flow

#1142 Only run delete-review-app if labelled with deploy
  .github/workflows/delete-review-app.yml
Labels: DevOps

#1143 Copy smoke tests from external repo
  .github/workflows/smoke-test.yml
  cypress.json
  cypress/fixtures/example.json
  cypress/fixtures/profile.json
  cypress/fixtures/users.json
  cypress/integration/find-teacher-training/basic.spec.ts
  cypress/integration/find-teacher-training/geocoding.spec.ts
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  package.json
  yarn.lock
Labels: deploy

#1149 [487] Increase deploy workflow timeout
  .github/workflows/deploy.yml
Labels: DevOps, deploy

#1158 Upgrade node from 12 to 16 and ruby from 2.7.2 to 2.7.5
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  package.json
  yarn.lock
Labels: deploy

#1178 Merge smoke test workflow into deploy workflow
  .github/workflows/deploy.yml
  .github/workflows/smoke-test.yml
Labels: deploy

#1188 Simplify support links in footer
  app/views/layouts/application.html.erb
Labels: deploy

#1189 Drop 3 of the subject checkboxes
  app/form_objects/search/subjects_form.rb
  spec/features/search/new_flow/across_england/secondary_spec.rb
Labels: deploy

#1187 Use tfvarsjson for workspace variables
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  Makefile
  terraform/workspace_variables/production.sh
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.sh
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/review.sh
  terraform/workspace_variables/review.tfvars
  terraform/workspace_variables/review.tfvars.json
  terraform/workspace_variables/sandbox.sh
  terraform/workspace_variables/sandbox.tfvars
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.sh
  terraform/workspace_variables/staging.tfvars
  terraform/workspace_variables/staging.tfvars.json
Labels: deploy

#1190 Update links to Get into teaching
  app/components/courses/financial_support/bursary_component.html.erb
  app/components/courses/financial_support/scholarship_and_bursary_component.html.erb
  app/views/courses/_advice.html.erb
  app/views/courses/financial_support/_bursary.html.erb
  app/views/courses/financial_support/_loan.html.erb
  app/views/courses/financial_support/_scholarship_and_bursary.html.erb
  app/views/result_filters/subject/_form.html.erb
  config/locales/en.yml
Labels: deploy
